# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - azurearyatewari

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://https://azurearyatewari.azurewebsites.net/
        username: ${{ secrets.AzureAppService_ContainerUsername_a50a974457394f1e8599505379f9a93e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5b62e07f02474a66ba3600803710e9f9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: https://azurearyatewari.azurewebsites.net/${{ secrets.AzureAppService_ContainerUsername_a50a974457394f1e8599505379f9a93e }}/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'azurearyatewari'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e4c5325716b64a3dba38ebadd9a28852 }}
        images: 'https://azurearyatewari.azurewebsites.net/${{ secrets.AzureAppService_ContainerUsername_a50a974457394f1e8599505379f9a93e }}/appsvc/wordpress-alpine-php:${{ github.sha }}'